version: '3.2'
services:
  backend1:
      image: basicexpress
      tty: true
      volumes:
        - "./00-basic-express-generator/app:/src/app"

  backend2:
      image:  basicexpress 
      tty: true
      volumes:
        - "./00-basic-express-generator/app:/src/app"

  backend3:
      image:   basicexpress
      tty: true
      volumes:
        - "./00-basic-express-generator/app:/src/app"

  loadbalancer:
      build: ./load-balancer
      tty: true
      links:
          - backend1
          - backend2
          - backend3
      ports:
          - '8089:8080'

volumes:
  backend:
